// Generated by https://quicktype.io

class Cast {
  List<Actor> actores = [];

  Cast.fromJsonList(List<dynamic> jsonList) {
    jsonList.forEach((item) {
      final actor = Actor.fromJsonMap(item);
      actores.add(actor);
    });
  }
}

class Actor {
  bool adult;
  int gender;
  int id;
  String name;
  String originalName;
  double popularity;
  String profilePath;
  int castId;
  String character;
  String creditId;
  int order;
  String job;

  Actor({
    required this.adult,
    required this.gender,
    required this.id,
    required this.name,
    required this.originalName,
    required this.popularity,
    required this.profilePath,
    required this.castId,
    required this.character,
    required this.creditId,
    required this.order,
    required this.job,
  });

  Actor.fromJsonMap(Map<String, dynamic> json)
      : adult = json['adult'],
        gender = json['gender'],
        id = json['id'],
        name = json['name'],
        originalName = json['original_name'],
        popularity = json['popularity'],
        profilePath = json['profile_path'] ??
            'https://institutogoldenprana.com.br/wp-content/uploads/2015/08/no-avatar-25359d55aa3c93ab3466622fd2ce712d1.jpg',
        castId = json['cast_id'],
        character = json['character'],
        creditId = json['credit_id'],
        order = json['order'],
        job = json['job'];

  getFoto() {
    return 'https://image.tmdb.org/t/p/w500/$profilePath';
  }
}
